In [1]:
import ast
import pandas as pd
import numpy as np
import scipy as sp
import scipy.sparse


In [2]:
import io
from contextlib import contextmanager


@contextmanager
def quote_brackets(filename):
    with open(filename) as f:
        yield io.StringIO(f.read().replace('[','"[').replace(']',']"'))

def combine_features(df):
    def str_cat_df(df,cols):
        series = (df[c] for c in cols)
        series = list(map(lambda x: x.apply(str), series))
        return series[0].str.cat(series[1:]).astype('category')
    
    author_features=['verified', 'activity', 'defaultprofile', 'userurl']
    tweet_features=['hashtag', 'tweeturl', 'mentions', 'media']
    
    df.insert(0,'author_feature',str_cat_df(df, author_features))
    df.insert(1,'tweet_feature',str_cat_df(df, tweet_features))
    
    df.drop(columns=author_features, inplace=True)
    df.drop(columns=tweet_features, inplace=True)

def normalize_level_column(colname):
    if colname.startswith('level'):
        return int(colname.removeprefix('level'))-1
    try:
        return int(colname)
    except ValueError:
        return colname
    
def normalized_csv(oldfile, newfile=None, numlevels=11):
    df = pd.read_csv(oldfile, dtype={'author_feature':'str','tweet_feature':'str'})
    if 'author_feature' not in df:
        combine_features(df)
    df.drop(columns=['author','tree','retweets'], inplace=True, errors='ignore')
    df.rename(mapper=normalize_level_column, axis=1, inplace=True)
    for l in range(numlevels):
        if l not in df:
            df[l]=0
    if newfile is not None:
        df.to_csv(newfile, index=False)
    return df
    


In [48]:
with quote_brackets('vegan_20210729_analysed.csv') as f:
    vegan_a=normalized_csv(f, 'vegan_analyzed.csv')
    
fpoe_a=normalized_csv('fpoeanalysed.csv','fpoe_analyzed.csv')
neos_a=normalized_csv('neos_20210729_analysed.csv','neos_analyzed.csv')

In [47]:
fpoe_g=normalized_csv('fpoe_generated.csv')
fpoe_p=normalized_csv('fpoe_with_params.csv')
neos_g=normalized_csv('results-trees-neos_20201110-2021-12-10T19:58:39.150768.csv')
neos_p=normalized_csv('neos_with_params.csv')

In [50]:
def by_feature(df):
    df=df.groupby(['author_feature', 'tweet_feature']).agg(['sum','mean',list])
    return df.dropna().swaplevel(axis=1).sort_index(axis=1)

In [49]:
fpoe_a=by_feature(fpoe_a)
neos_a=by_feature(neos_a)
fpoe_g=by_feature(fpoe_g)
fpoe_p=by_feature(fpoe_p)
neos_g=by_feature(neos_g)
neos_p=by_feature(neos_p)

In [216]:
def mean(a, b):
    return (a['mean'] - b['mean']).dropna().mean(axis=1)

def compare(a,b):
    m=mean(a,b)
    return {'mae':m.abs().mean(),
            'me':m.mean(),
            'mywasserstein_levels': observed_levels_distance(a,b, lambda u,v:wasserstein_2d(np.array([u]).transpose(),np.array([v]).transpose())).mean(),
            'mwasserstein_levels': mean_levels_distance(a,b, scipy.stats.wasserstein_distance).mean(),
            'menergy_levels': mean_levels_distance(a,b, scipy.stats.energy_distance).mean()
           }

def table(analyzed, without_params, with_params):
    return pd.DataFrame([compare(analyzed,without_params),compare(analyzed,with_params)],index=['without params', 'with params'])

mean(neos_p,neos_a).mean()
#by_feature(neos_a).loc[('0000','0001')]

-0.10922888427086508

In [217]:
table(fpoe_a,fpoe_g,fpoe_p)    

mae        me  mywasserstein_levels  mwasserstein_levels  \
without params  0.553913  0.514472              0.587123             0.393364   
with params     0.268906  0.137954              0.882816             0.486923   

                menergy_levels  
without params        0.349402  
with params           0.493684

In [166]:
table(neos_a, neos_g, neos_p)    

mae        me  mwasserstein_levels  menergy_levels
without params  0.437720  0.330634             0.379652        0.360213
with params     0.247649  0.109229             0.477714        0.522775

In [253]:
import scipy.stats

def observed_levels(df):
    df=df['sum']
    return df.apply(lambda x: [l for c in df.columns for l in [c]*x[c]], axis=1)

def observed_levels_distance(a, b, distance=scipy.stats.wasserstein_distance):
    df=pd.DataFrame({'a':observed_levels(a), 'b':observed_levels(b)}).dropna()
    return df.apply(lambda x:distance(*x),axis=1)

def mean_levels_distance(a, b, distance=scipy.stats.wasserstein_distance):
    df=pd.concat([a['mean'],b['mean']],keys=['a','b'],axis=1).dropna()
    columns=a['mean'].columns
    return df.apply(lambda x: distance(columns,columns,x['a'],x['b']),axis=1)

mean_levels_distance(fpoe_a,fpoe_p).mean()
observed_levels_distance(fpoe_a,fpoe_p).mean()
#len(observed_levels(fpoe_a)[('0000','0000')])

0.48692311212143624

In [258]:
# https://stackoverflow.com/a/57563383/
from scipy.spatial.distance import cdist
from scipy.optimize import linear_sum_assignment

def wasserstein_2d(U,V, normalize=True):
    if normalize:
        U = U#/U.shape[0]#U.sum().sum()
        V = V#/V.shape[0]#V.sum().sum()
    d = cdist(U,V)
    display(d)

    assignment = linear_sum_assignment(d)
    return d[assignment].sum()#/(U.sum().sum()+V.sum().sum())

def wasserstein_2d_row_ab(row, normalize=False):
    a=np.array(row['a'].to_list()).transpose()
    b=np.array(row['b'].to_list()).transpose()
    return wasserstein_2d(a,b,normalize)

def wasserstein_2d_df(a,b,normalize=False):
    a=a['list']
    b=b['list']
#     a=pd.Series([observed_levels(a)])
#     b=pd.Series([observed_levels(b)])
    df=pd.concat([a,b], keys=['a','b'], axis=1).dropna()
#     display(df)
    return df.apply(wasserstein_2d_row_ab, axis=1, normalize=normalize)

# display(observed_levels_distance(fpoe_a,fpoe_p))

wasserstein_2d_df(fpoe_a,fpoe_g,True)
# mine=observed_levels_distance(fpoe_a,fpoe_g, lambda u,v:wasserstein_2d(np.array([u]).transpose(),np.array([v]).transpose()))
# orig=observed_levels_distance(fpoe_a,fpoe_g)
# mine.loc[('0000','0000')]/orig.loc[('0000','0000')]

#neos_a['list']
# neos_a['mean'].applymap(lambda x:[x])
#pd.DataFrame([a,b],index=['a','b']).fillna([0])
#pd.DataFrame(a.array)
#np.array(neos_a['list'].loc[('0000','0001')].apply(lambda x:[np.mean(x)]))
#neos_a['mean'].loc[('0000','0001')].apply(lambda x:[x]).to_list()
#by_feature(neos_g)['list']
#fpoe_a['mean'].loc[('0000','0000')].sum()
# np.array(neos_a['list'].loc[('0000','0001')].to_list()).transpose().shape[0]

array([[1.41421356, 1.        , 1.41421356, ..., 1.        , 1.        ,
        1.        ],
       [2.        , 3.        , 2.        , ..., 3.        , 3.        ,
        3.        ],
       [1.        , 0.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [1.        , 0.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       [1.41421356, 1.        , 1.41421356, ..., 1.        , 1.        ,
        1.        ],
       [1.41421356, 1.        , 1.41421356, ..., 1.        , 1.        ,
        1.        ]])

array([[0.        , 1.        , 1.        , ..., 1.        , 0.        ,
        0.        ],
       [8.30662386, 8.24621125, 8.24621125, ..., 8.24621125, 8.30662386,
        8.30662386],
       [0.        , 1.        , 1.        , ..., 1.        , 0.        ,
        0.        ],
       ...,
       [1.        , 0.        , 0.        , ..., 0.        , 1.        ,
        1.        ],
       [0.        , 1.        , 1.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 1.        , 1.        , ..., 1.        , 0.        ,
        0.        ]])

array([[ 1.        ,  1.        ,  1.        , ...,  1.        ,
         1.        ,  1.        ],
       [10.        , 10.        , 10.        , ..., 10.        ,
        10.        , 10.        ],
       [ 8.36660027,  8.36660027,  8.36660027, ...,  8.36660027,
         8.36660027,  8.36660027],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 5.91607978,  5.91607978,  5.91607978, ...,  5.91607978,
         5.91607978,  5.91607978],
       [ 1.41421356,  1.41421356,  1.41421356, ...,  1.41421356,
         1.41421356,  1.41421356]])

array([[48.52834223, 48.64154603, 48.64154603, 48.52834223, 48.31148932,
        48.64154603, 48.64154603, 48.64154603, 48.52834223, 48.64154603,
        48.64154603, 48.52834223, 48.64154603, 48.64154603, 48.52834223,
        48.64154603, 48.64154603, 48.52834223, 48.64154603, 48.52834223,
        48.52834223, 48.64154603, 48.52834223, 48.64154603, 48.64154603,
        48.64154603, 48.64154603, 48.64154603, 48.64154603, 48.64154603,
        48.52834223, 48.43552415, 48.64154603, 48.52834223, 48.52834223,
        48.64154603, 48.64154603, 48.43552415, 48.64154603, 48.64154603,
        48.52834223, 48.43552415, 48.52834223, 48.64154603, 48.02082881,
        48.64154603, 48.64154603, 47.93745926, 48.43552415, 48.64154603,
        48.64154603, 48.64154603, 48.52834223, 48.64154603, 48.64154603,
        48.52834223, 48.64154603, 48.43552415, 48.52834223, 48.52834223,
        48.52834223, 48.64154603, 48.64154603, 48.52834223, 48.31148932,
        48.43552415, 48.64154603, 48.52834223, 48.4

array([[1.        , 1.41421356, 1.        , ..., 1.        , 1.        ,
        1.41421356],
       [0.        , 1.        , 0.        , ..., 0.        , 0.        ,
        1.        ],
       [2.23606798, 1.41421356, 2.23606798, ..., 2.23606798, 2.23606798,
        1.41421356],
       ...,
       [1.        , 1.41421356, 1.        , ..., 1.        , 1.        ,
        1.41421356],
       [3.        , 2.        , 3.        , ..., 3.        , 3.        ,
        2.        ],
       [1.        , 0.        , 1.        , ..., 1.        , 1.        ,
        0.        ]])

array([[1.41421356, 1.41421356, 1.41421356, ..., 1.41421356, 1.41421356,
        1.41421356],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       ...,
       [6.40312424, 6.40312424, 6.40312424, ..., 6.40312424, 6.40312424,
        6.40312424],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [2.        , 2.        , 2.        , ..., 2.        , 2.        ,
        2.        ]])

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.41421356],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.41421356],
       [2.82842712, 2.82842712, 2.82842712, ..., 2.82842712, 2.82842712,
        1.41421356],
       ...,
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.73205081],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.41421356],
       [1.41421356, 1.41421356, 1.41421356, ..., 1.41421356, 1.41421356,
        1.41421356]])

array([[1.41421356, 1.41421356, 1.        , ..., 1.        , 1.        ,
        1.        ],
       [9.2736185 , 9.2736185 , 9.43398113, ..., 9.43398113, 9.43398113,
        9.43398113],
       [1.41421356, 1.41421356, 1.        , ..., 1.        , 1.        ,
        1.        ],
       ...,
       [1.41421356, 1.41421356, 2.23606798, ..., 2.23606798, 2.23606798,
        2.23606798],
       [0.        , 0.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [0.        , 0.        , 1.        , ..., 1.        , 1.        ,
        1.        ]])

array([[1.        , 1.        , 1.        , ..., 3.74165739, 1.        ,
        1.        ],
       [1.        , 1.        , 1.        , ..., 3.74165739, 1.        ,
        1.        ],
       [3.60555128, 3.60555128, 3.60555128, ..., 2.82842712, 3.60555128,
        3.60555128],
       ...,
       [0.        , 0.        , 0.        , ..., 3.60555128, 0.        ,
        0.        ],
       [2.23606798, 2.23606798, 2.23606798, ..., 3.46410162, 2.23606798,
        2.23606798],
       [0.        , 0.        , 0.        , ..., 3.60555128, 0.        ,
        0.        ]])

array([[1.        , 1.41421356, 3.16227766, ..., 1.41421356, 1.        ,
        2.23606798],
       [0.        , 1.        , 3.        , ..., 1.        , 0.        ,
        2.        ],
       [0.        , 1.        , 3.        , ..., 1.        , 0.        ,
        2.        ],
       ...,
       [0.        , 1.        , 3.        , ..., 1.        , 0.        ,
        2.        ],
       [9.48683298, 9.        , 8.30662386, ..., 9.        , 9.48683298,
        8.60232527],
       [4.47213595, 3.60555128, 2.23606798, ..., 3.60555128, 4.47213595,
        2.82842712]])

array([[ 1.        ,  0.        ,  1.        , ...,  1.        ,
         0.        ,  1.        ],
       [12.08304597, 11.18033989, 12.08304597, ..., 12.08304597,
        11.18033989, 12.08304597],
       [ 3.60555128,  3.16227766,  3.60555128, ...,  3.60555128,
         3.16227766,  3.60555128],
       ...,
       [ 1.        ,  1.41421356,  1.        , ...,  1.        ,
         1.41421356,  1.        ],
       [ 0.        ,  1.        ,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       [ 1.        ,  1.41421356,  1.        , ...,  1.        ,
         1.41421356,  1.        ]])

array([[2.23606798, 2.44948974, 3.        , 1.        , 1.41421356,
        1.        , 1.        , 1.41421356, 2.23606798, 1.41421356,
        1.41421356, 1.        , 1.41421356, 2.44948974, 1.        ,
        2.23606798, 1.        , 1.41421356, 3.16227766, 2.23606798,
        1.41421356, 1.        , 1.        , 3.31662479, 1.        ,
        1.        , 4.58257569, 2.44948974, 1.41421356, 2.23606798,
        4.24264069, 2.23606798, 1.41421356, 1.        , 1.41421356,
        1.        , 1.        , 1.        , 2.23606798, 1.        ,
        3.        , 1.41421356, 2.23606798, 1.        , 4.12310563,
        2.23606798, 1.        , 1.        , 2.23606798, 1.        ,
        3.16227766, 1.        , 1.41421356, 1.41421356, 1.        ,
        1.        , 4.35889894, 2.44948974, 1.        , 3.16227766,
        1.41421356, 1.41421356, 1.73205081, 1.41421356, 1.41421356,
        1.        , 1.41421356, 1.        , 1.        , 1.        ,
        1.        , 1.41421356, 2.23606798],
   

array([[ 2.82842712,  2.23606798,  2.        , ...,  2.        ,
         2.        ,  2.        ],
       [ 1.41421356,  1.        ,  1.41421356, ...,  1.41421356,
         1.41421356,  1.41421356],
       [ 2.        ,  1.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 2.        ,  1.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 3.16227766,  3.60555128,  4.24264069, ...,  4.24264069,
         4.24264069,  4.24264069],
       [ 8.66025404,  9.48683298, 10.34408043, ..., 10.34408043,
        10.34408043, 10.34408043]])

array([[1.        , 0.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [2.82842712, 2.23606798, 2.82842712, ..., 2.82842712, 2.82842712,
        2.82842712],
       [1.        , 1.41421356, 1.        , ..., 1.        , 1.        ,
        1.        ],
       ...,
       [0.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [4.        , 4.12310563, 4.        , ..., 4.        , 4.        ,
        4.        ],
       [0.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

array([[2.        , 1.        , 2.        , ..., 2.        , 2.        ,
        1.        ],
       [6.40312424, 5.83095189, 6.40312424, ..., 6.40312424, 6.40312424,
        5.83095189],
       [0.        , 1.        , 0.        , ..., 0.        , 0.        ,
        1.        ],
       ...,
       [2.23606798, 2.        , 2.23606798, ..., 2.23606798, 2.23606798,
        2.        ],
       [6.164414  , 5.74456265, 6.164414  , ..., 6.164414  , 6.164414  ,
        5.74456265],
       [1.        , 0.        , 1.        , ..., 1.        , 1.        ,
        0.        ]])

array([[ 1.        ,  1.        ,  1.41421356, ...,  1.        ,
         1.        ,  1.41421356],
       [ 0.        ,  0.        ,  1.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 0.        ,  0.        ,  1.        , ...,  0.        ,
         0.        ,  1.        ],
       ...,
       [15.8113883 , 15.8113883 , 15.65247584, ..., 15.8113883 ,
        15.8113883 , 15.65247584],
       [ 0.        ,  0.        ,  1.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 0.        ,  0.        ,  1.        , ...,  0.        ,
         0.        ,  1.        ]])

array([[ 5.09901951,  5.09901951,  5.09901951, ...,  5.        ,
         5.09901951,  5.09901951],
       [ 6.40312424,  6.40312424,  6.40312424, ...,  6.32455532,
         6.40312424,  6.40312424],
       [40.95119046, 40.95119046, 40.90232267, ..., 40.91454509,
        40.90232267, 40.90232267],
       ...,
       [ 2.82842712,  2.82842712,  2.        , ...,  2.23606798,
         2.        ,  2.        ],
       [ 2.        ,  2.        ,  0.        , ...,  1.        ,
         0.        ,  0.        ],
       [ 1.        ,  1.        ,  2.23606798, ...,  1.41421356,
         2.23606798,  2.23606798]])

array([[1.41421356, 1.41421356, 1.41421356, ..., 1.41421356, 1.41421356,
        1.41421356],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        2.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        2.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        2.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        2.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        2.        ]])

array([[ 3.74165739,  3.74165739,  3.60555128, ...,  3.74165739,
         2.82842712,  3.74165739],
       [ 2.        ,  2.        ,  1.        , ...,  0.        ,
         1.41421356,  0.        ],
       [10.19803903, 10.19803903, 10.44030651, ..., 10.77032961,
        10.48808848, 10.77032961],
       ...,
       [ 2.        ,  2.        ,  1.        , ...,  0.        ,
         1.41421356,  0.        ],
       [15.65247584, 15.65247584, 16.1245155 , ..., 16.64331698,
        16.15549442, 16.64331698],
       [25.57342371, 25.57342371, 25.55386468, ..., 25.57342371,
        25.05992817, 25.57342371]])

array([[ 0.        ,  0.        ,  0.        , ...,  1.        ,
         1.        ,  0.        ],
       [22.64950331, 22.64950331, 22.64950331, ..., 22.36067977,
        22.36067977, 22.64950331],
       [ 1.        ,  1.        ,  1.        , ...,  1.41421356,
         1.41421356,  1.        ],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  1.        ,
         1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  1.        ,
         1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  1.        ,
         1.        ,  0.        ]])

array([[ 1.        ,  1.        ,  1.        ,  2.        ,  2.        ,
         0.        ,  2.        ,  2.        ,  1.        ,  0.        ,
         2.        ,  3.        ,  1.        ,  2.        ,  1.41421356,
         1.        ,  2.        ,  2.82842712,  1.        ,  1.        ,
         3.60555128,  2.        ,  1.        ,  1.        ,  1.        ,
         2.        ,  1.        ,  1.        ,  2.        ,  2.        ,
         1.        ,  1.        ,  2.        ,  2.        ,  1.        ,
         1.        ,  2.        ,  2.        ,  0.        ,  1.        ,
         0.        ,  2.        ,  0.        ,  2.        ,  2.        ,
         2.        ,  1.        ,  2.        ,  2.        ,  2.        ,
         1.        ,  3.        ,  1.        ,  2.        ,  1.        ],
       [18.60107524, 18.60107524, 18.70828693, 18.62793601, 18.62793601,
        18.62793601, 18.62793601, 18.62793601, 18.60107524, 18.62793601,
        18.62793601, 17.02938637, 18.70828693, 18.

array([[1.        , 0.        , 1.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 1.        , 0.        ,
        1.        ],
       [0.        , 1.        , 0.        , ..., 1.        , 0.        ,
        1.        ],
       ...,
       [0.        , 1.        , 0.        , ..., 1.        , 0.        ,
        1.        ],
       [1.        , 0.        , 1.        , ..., 0.        , 1.        ,
        0.        ],
       [1.41421356, 1.        , 1.41421356, ..., 1.        , 1.41421356,
        1.        ]])

array([[0.        , 4.58257569, 1.        , ..., 4.        , 1.        ,
        0.        ],
       [0.        , 4.58257569, 1.        , ..., 4.        , 1.        ,
        0.        ],
       [0.        , 4.58257569, 1.        , ..., 4.        , 1.        ,
        0.        ],
       ...,
       [0.        , 4.58257569, 1.        , ..., 4.        , 1.        ,
        0.        ],
       [1.41421356, 4.35889894, 1.        , ..., 3.16227766, 1.        ,
        1.41421356],
       [0.        , 4.58257569, 1.        , ..., 4.        , 1.        ,
        0.        ]])

array([[ 4.12310563,  4.12310563,  4.24264069, ...,  4.        ,
         4.12310563,  4.12310563],
       [ 0.        ,  0.        ,  2.23606798, ...,  1.        ,
         0.        ,  0.        ],
       [ 1.        ,  1.        ,  1.41421356, ...,  0.        ,
         1.        ,  1.        ],
       ...,
       [ 1.73205081,  1.73205081,  1.41421356, ...,  1.41421356,
         1.73205081,  1.73205081],
       [ 3.        ,  3.        ,  1.41421356, ...,  2.        ,
         3.        ,  3.        ],
       [20.54263858, 20.54263858, 19.10497317, ..., 19.8242276 ,
        20.54263858, 20.54263858]])

array([[0.        , 1.        , 0.        , ..., 2.        , 1.        ,
        1.        ],
       [0.        , 1.        , 0.        , ..., 2.        , 1.        ,
        1.        ],
       [1.41421356, 1.        , 1.41421356, ..., 1.41421356, 1.        ,
        1.        ],
       ...,
       [1.41421356, 1.        , 1.41421356, ..., 1.41421356, 1.        ,
        1.        ],
       [3.16227766, 3.        , 3.16227766, ..., 3.16227766, 3.        ,
        3.        ],
       [1.73205081, 1.41421356, 1.73205081, ..., 1.73205081, 1.41421356,
        1.41421356]])

array([[2.        , 2.23606798, 2.        , ..., 2.        , 2.        ,
        2.82842712],
       [1.        , 1.41421356, 1.        , ..., 1.        , 1.        ,
        2.23606798],
       [3.        , 2.        , 3.        , ..., 3.        , 3.        ,
        1.        ],
       ...,
       [8.1240384 , 8.06225775, 8.1240384 , ..., 8.1240384 , 8.1240384 ,
        8.1240384 ],
       [1.73205081, 1.41421356, 1.73205081, ..., 1.73205081, 1.73205081,
        1.73205081],
       [3.        , 2.        , 3.        , ..., 3.        , 3.        ,
        1.        ]])

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         1.        ,  2.23606798],
       [ 2.        ,  2.        ,  2.        , ...,  2.        ,
         1.        ,  1.        ],
       [14.2126704 , 14.2126704 , 14.2126704 , ..., 14.2126704 ,
        13.45362405, 12.76714533],
       ...,
       [ 1.        ,  1.        ,  1.        , ...,  1.        ,
         1.41421356,  2.44948974],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         1.        ,  2.23606798],
       [ 1.        ,  1.        ,  1.        , ...,  1.        ,
         0.        ,  1.41421356]])

array([[46.10856753, 46.36809248, 46.36809248, ..., 46.36809248,
        46.32493929, 46.33573135],
       [ 1.41421356,  0.        ,  0.        , ...,  0.        ,
         2.        ,  1.        ],
       [ 2.23606798,  2.23606798,  2.23606798, ...,  2.23606798,
         2.23606798,  2.        ],
       ...,
       [ 1.        ,  1.        ,  1.        , ...,  1.        ,
         1.        ,  0.        ],
       [ 4.24264069,  5.47722558,  5.47722558, ...,  5.47722558,
         3.74165739,  4.58257569],
       [ 1.41421356,  2.        ,  2.        , ...,  2.        ,
         0.        ,  1.        ]])

array([[2.        , 1.        , 1.        , ..., 4.        , 2.        ,
        0.        ],
       [2.        , 1.        , 1.        , ..., 4.        , 2.        ,
        0.        ],
       [2.23606798, 1.41421356, 1.41421356, ..., 4.12310563, 2.23606798,
        1.        ],
       ...,
       [2.        , 1.        , 1.        , ..., 4.        , 2.        ,
        0.        ],
       [2.82842712, 2.23606798, 2.23606798, ..., 4.47213595, 2.82842712,
        2.        ],
       [2.        , 1.        , 1.        , ..., 4.        , 2.        ,
        0.        ]])

array([[1.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [1.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [1.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [1.41421356, 1.41421356, 1.        , ..., 1.        , 1.        ,
        1.        ],
       [1.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [1.41421356, 1.41421356, 1.        , ..., 1.        , 1.        ,
        1.        ]])

array([[ 2.23606798,  2.23606798,  2.        , ...,  2.23606798,
         2.        ,  2.        ],
       [ 2.23606798,  2.23606798,  2.        , ...,  2.23606798,
         2.        ,  2.        ],
       [ 9.8488578 ,  9.8488578 , 10.29563014, ...,  9.8488578 ,
        10.29563014, 10.29563014],
       ...,
       [ 0.        ,  0.        ,  1.        , ...,  0.        ,
         1.        ,  1.        ],
       [ 3.16227766,  3.16227766,  3.60555128, ...,  3.16227766,
         3.60555128,  3.60555128],
       [ 1.        ,  1.        ,  0.        , ...,  1.        ,
         0.        ,  0.        ]])

array([[0.        , 1.        , 2.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 1.        , 2.        , ..., 1.        , 0.        ,
        0.        ],
       [1.        , 1.41421356, 2.23606798, ..., 1.41421356, 1.        ,
        1.        ],
       ...,
       [0.        , 1.        , 2.        , ..., 1.        , 0.        ,
        0.        ],
       [3.60555128, 3.16227766, 3.        , ..., 3.16227766, 3.60555128,
        3.60555128],
       [1.        , 0.        , 1.        , ..., 0.        , 1.        ,
        1.        ]])

array([[2.23606798, 2.        , 2.82842712, ..., 2.23606798, 2.44948974,
        2.23606798],
       [1.        , 0.        , 2.        , ..., 1.        , 1.41421356,
        1.        ],
       [1.        , 1.41421356, 1.41421356, ..., 1.        , 1.41421356,
        1.        ],
       ...,
       [1.        , 0.        , 2.        , ..., 1.        , 1.41421356,
        1.        ],
       [1.        , 0.        , 2.        , ..., 1.        , 1.41421356,
        1.        ],
       [2.        , 2.23606798, 2.23606798, ..., 2.        , 2.23606798,
        2.        ]])

array([[1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [1.73205081, 1.73205081, 1.73205081, ..., 1.73205081, 1.73205081,
        1.73205081],
       ...,
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [3.        , 3.        , 3.        , ..., 3.        , 3.        ,
        3.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

array([[0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 1.41421356,
        1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 1.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.        , 0.        , 0.  

array([[ 5.09901951,  5.09901951,  4.12310563, ...,  5.09901951,
         5.09901951,  5.09901951],
       [ 0.        ,  0.        ,  1.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 7.81024968,  7.81024968,  7.21110255, ...,  7.81024968,
         7.81024968,  7.81024968],
       [ 1.        ,  1.        ,  1.41421356, ...,  1.        ,
         1.        ,  1.        ],
       [11.40175425, 11.40175425, 10.81665383, ..., 11.40175425,
        11.40175425, 11.40175425]])

array([[7.21110255, 7.28010989, 7.28010989, ..., 7.28010989, 7.28010989,
        7.28010989],
       [1.        , 1.41421356, 1.41421356, ..., 1.41421356, 1.41421356,
        1.41421356],
       [1.41421356, 1.        , 1.        , ..., 1.        , 2.23606798,
        1.        ],
       ...,
       [6.08276253, 6.        , 6.        , ..., 6.        , 6.32455532,
        6.        ],
       [1.41421356, 1.        , 1.        , ..., 1.        , 2.23606798,
        1.        ],
       [1.        , 0.        , 0.        , ..., 0.        , 2.        ,
        0.        ]])

array([[0.        , 0.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [1.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [1.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [1.41421356, 1.41421356, 1.        , ..., 1.        , 1.        ,
        1.        ],
       [0.        , 0.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [1.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

array([[ 1.        ,  1.        ,  1.        , ...,  1.        ,
         1.        ,  1.        ],
       [ 3.        ,  3.        ,  3.        , ...,  3.        ,
         3.        ,  3.        ],
       [ 3.        ,  3.        ,  3.        , ...,  3.        ,
         3.        ,  3.        ],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [26.2488095 , 26.2488095 , 26.2488095 , ..., 26.2488095 ,
        26.2488095 , 26.2488095 ],
       [ 2.23606798,  2.23606798,  2.23606798, ...,  2.23606798,
         2.23606798,  2.23606798]])

array([[1.73205081, 1.73205081, 1.41421356, ..., 1.73205081, 1.73205081,
        1.73205081],
       [2.23606798, 1.        , 0.        , ..., 1.        , 1.        ,
        1.        ],
       [3.16227766, 2.        , 2.23606798, ..., 2.        , 2.        ,
        2.82842712],
       ...,
       [2.44948974, 0.        , 1.        , ..., 0.        , 0.        ,
        2.        ],
       [2.44948974, 0.        , 1.        , ..., 0.        , 0.        ,
        2.        ],
       [2.44948974, 0.        , 1.        , ..., 0.        , 0.        ,
        2.        ]])

array([[0.        , 0.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       [2.23606798, 2.23606798, 1.41421356, ..., 2.23606798, 2.23606798,
        2.23606798],
       [0.        , 0.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.        , 0.        ,
        0.        ]])

array([[ 0.        ,  0.        ,  1.        , ...,  0.        ,
         1.        ,  2.23606798],
       [ 0.        ,  0.        ,  1.        , ...,  0.        ,
         1.        ,  2.23606798],
       [ 0.        ,  0.        ,  1.        , ...,  0.        ,
         1.        ,  2.23606798],
       ...,
       [ 2.23606798,  2.23606798,  1.41421356, ...,  2.23606798,
         1.41421356,  1.41421356],
       [12.80624847, 12.80624847, 12.20655562, ..., 12.80624847,
        12.20655562, 11.70469991],
       [ 3.16227766,  3.16227766,  3.        , ...,  3.16227766,
         3.        ,  3.31662479]])

array([[1.        , 1.41421356, 1.        , ..., 1.        , 1.        ,
        1.        ],
       [1.        , 1.41421356, 1.        , ..., 1.        , 1.        ,
        1.        ],
       [0.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [2.23606798, 1.41421356, 2.23606798, ..., 2.23606798, 2.23606798,
        2.23606798],
       [0.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

array([[ 2.23606798,  1.        ,  1.        , ...,  1.        ,
         1.41421356,  1.        ],
       [17.29161647, 18.1934054 , 18.1934054 , ..., 18.1934054 ,
        17.72004515, 18.1934054 ],
       [ 2.        ,  0.        ,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [ 2.        ,  0.        ,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       [ 2.        ,  0.        ,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       [ 1.        ,  1.        ,  1.        , ...,  1.        ,
         0.        ,  1.        ]])

array([[21.67948339, 21.9317122 , 21.9317122 , ..., 21.9317122 ,
        21.67948339, 21.47091055],
       [ 1.41421356,  1.        ,  1.        , ...,  1.        ,
         1.41421356,  2.23606798],
       [ 1.41421356,  2.23606798,  2.23606798, ...,  2.23606798,
         1.41421356,  1.        ],
       ...,
       [ 1.        ,  1.41421356,  1.41421356, ...,  1.41421356,
         1.        ,  1.41421356],
       [45.39823785, 45.49725266, 45.49725266, ..., 45.49725266,
        45.39823785, 45.32107677],
       [ 0.        ,  1.        ,  1.        , ...,  1.        ,
         0.        ,  1.        ]])

array([[ 2.        ,  1.        ,  1.        , ...,  1.        ,
         1.        ,  0.        ],
       [ 2.23606798,  2.        ,  2.        , ...,  2.        ,
         2.        ,  2.23606798],
       [26.28687886, 26.4952826 , 26.4952826 , ..., 26.4952826 ,
        26.4952826 , 26.73948391],
       ...,
       [13.74772708, 14.2126704 , 14.2126704 , ..., 14.2126704 ,
        14.2126704 , 14.73091986],
       [ 2.23606798,  1.41421356,  1.41421356, ...,  1.41421356,
         1.41421356,  1.        ],
       [15.77973384, 15.93737745, 15.93737745, ..., 15.93737745,
        15.93737745, 16.15549442]])

array([[ 2.        ,  4.47213595,  2.        ,  1.        ,  2.        ,
         1.41421356,  2.        ,  1.        ,  1.        ,  2.        ,
         2.        ,  0.        ,  1.        ,  1.        ,  1.        ,
         2.        ,  2.        ,  0.        ,  1.        ,  1.        ,
         2.        ,  1.        ,  2.        ,  3.16227766,  3.        ,
         2.        ,  0.        ,  2.        ,  1.        ,  2.        ,
         1.        ,  2.        ,  1.        ,  1.41421356,  1.        ,
         1.        ,  1.        ,  0.        ,  1.        ,  1.        ,
         3.        ,  2.        ,  0.        ,  1.        ,  2.        ,
         2.        ,  1.        ,  1.41421356,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  2.        ,  2.        ,
         2.        ,  1.41421356,  2.        ,  2.        ,  1.        ,
         1.        ,  0.        ,  1.        ,  2.        ,  1.        ,
         2.23606798,  0.        ,  1.        ,  2. 

array([[1.        , 1.        , 0.        , ..., 0.        , 2.        ,
        0.        ],
       [1.        , 1.        , 0.        , ..., 0.        , 2.        ,
        0.        ],
       [1.41421356, 1.41421356, 1.        , ..., 1.        , 2.23606798,
        1.        ],
       ...,
       [0.        , 0.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [1.        , 1.        , 0.        , ..., 0.        , 2.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 1.        , 1.        ,
        1.        ]])

array([[0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [6.32455532, 6.32455532, 6.32455532, ..., 5.38516481, 6.32455532,
        6.32455532],
       [3.60555128, 3.60555128, 3.60555128, ..., 3.16227766, 3.60555128,
        3.60555128],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [1.        , 1.        , 1.        , ..., 0.        , 1.        ,
        1.        ],
       [8.94427191, 8.94427191, 8.94427191, ..., 8.54400375, 8.94427191,
        8.94427191]])

array([[1.41421356, 1.41421356, 1.        , ..., 1.41421356, 1.        ,
        1.41421356],
       [0.        , 0.        , 1.        , ..., 0.        , 1.        ,
        0.        ],
       [5.        , 5.        , 5.09901951, ..., 5.        , 5.09901951,
        5.        ],
       ...,
       [7.68114575, 7.68114575, 7.61577311, ..., 7.68114575, 7.61577311,
        7.68114575],
       [0.        , 0.        , 1.        , ..., 0.        , 1.        ,
        0.        ],
       [2.23606798, 2.23606798, 1.41421356, ..., 2.23606798, 1.41421356,
        2.23606798]])

array([[ 1.        ,  1.        ,  2.23606798, ...,  1.41421356,
         1.41421356,  2.23606798],
       [57.72347876, 57.72347876, 55.85696018, ..., 56.78908346,
        56.78908346, 55.85696018],
       [ 0.        ,  0.        ,  2.        , ...,  1.        ,
         1.        ,  2.        ],
       ...,
       [17.8325545 , 17.8325545 , 16.30950643, ..., 17.05872211,
        17.05872211, 16.30950643],
       [ 1.        ,  1.        ,  1.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 0.        ,  0.        ,  2.        , ...,  1.        ,
         1.        ,  2.        ]])

array([[7.48331477, 7.81024968, 7.28010989, ..., 7.21110255, 7.21110255,
        7.81024968],
       [0.        , 1.        , 1.        , ..., 2.        , 2.        ,
        1.        ],
       [8.54400375, 8.94427191, 8.24621125, ..., 8.06225775, 8.06225775,
        8.94427191],
       ...,
       [1.        , 0.        , 2.        , ..., 3.        , 3.        ,
        0.        ],
       [1.        , 0.        , 2.        , ..., 3.        , 3.        ,
        0.        ],
       [1.41421356, 1.        , 2.23606798, ..., 3.16227766, 3.16227766,
        1.        ]])

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       [ 4.47213595,  4.47213595,  4.47213595, ...,  4.47213595,
         4.12310563,  4.47213595],
       [10.        , 10.        , 10.        , ..., 10.        ,
         9.43398113, 10.        ],
       ...,
       [ 1.        ,  1.        ,  1.        , ...,  1.        ,
         1.41421356,  1.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       [ 3.        ,  3.        ,  3.        , ...,  3.        ,
         2.82842712,  3.        ]])

array([[1.41421356, 1.        , 1.        , ..., 1.41421356, 1.        ,
        1.41421356],
       [1.        , 0.        , 0.        , ..., 1.        , 0.        ,
        1.        ],
       [1.        , 0.        , 0.        , ..., 1.        , 0.        ,
        1.        ],
       ...,
       [2.        , 2.23606798, 2.23606798, ..., 2.        , 2.23606798,
        2.        ],
       [1.41421356, 1.        , 1.        , ..., 1.41421356, 1.        ,
        1.41421356],
       [1.41421356, 1.        , 1.        , ..., 1.41421356, 1.        ,
        1.41421356]])

array([[3.16227766, 3.16227766, 3.16227766, ..., 3.16227766, 3.16227766,
        3.        ],
       [0.        , 2.        , 0.        , ..., 0.        , 0.        ,
        1.        ],
       [0.        , 2.        , 0.        , ..., 0.        , 0.        ,
        1.        ],
       ...,
       [0.        , 2.        , 0.        , ..., 0.        , 0.        ,
        1.        ],
       [0.        , 2.        , 0.        , ..., 0.        , 0.        ,
        1.        ],
       [2.23606798, 2.23606798, 2.23606798, ..., 2.23606798, 2.23606798,
        2.        ]])

array([[0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [2.44948974, 2.44948974, 2.44948974, ..., 2.23606798, 2.44948974,
        2.44948974],
       ...,
       [1.41421356, 1.41421356, 1.41421356, ..., 1.        , 1.41421356,
        1.41421356],
       [2.23606798, 2.23606798, 2.23606798, ..., 1.41421356, 2.23606798,
        2.23606798],
       [9.43398113, 9.43398113, 9.43398113, ..., 9.2736185 , 9.43398113,
        9.43398113]])

array([[1.        , 0.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [8.06225775, 8.        , 8.06225775, ..., 8.06225775, 8.06225775,
        8.06225775],
       [1.        , 1.41421356, 2.23606798, ..., 2.23606798, 2.23606798,
        2.23606798],
       ...,
       [2.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [1.        , 1.41421356, 2.23606798, ..., 2.23606798, 2.23606798,
        2.23606798],
       [2.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

array([[0.        , 0.        , 0.        , 8.66025404, 4.        ,
        1.        , 2.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 2.23606798, 1.        , 1.        , 1.        ,
        1.        , 4.        , 2.23606798, 2.        , 1.        ,
        2.        , 3.        , 1.        , 1.        , 1.        ,
        1.        , 3.        , 1.41421356, 0.        , 2.23606798,
        2.        , 2.        , 1.        , 2.        , 2.        ,
        0.        , 1.        , 0.        , 2.        , 1.        ,
        2.        , 2.        , 1.        , 0.        , 0.        ,
        2.        , 1.        , 1.        , 1.        , 7.21110255,
        0.        , 0.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        ],
       [1.41421356, 1.41421356, 1.41421356, 9.32737905, 4.47213595,
        1.        , 2.44948974, 1.        , 2.23606798, 1. 

array([[2.23606798, 2.        , 2.23606798, ..., 2.23606798, 2.23606798,
        2.23606798],
       [2.23606798, 1.41421356, 2.23606798, ..., 2.23606798, 2.23606798,
        2.23606798],
       [0.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [1.        , 1.41421356, 1.        , ..., 1.        , 1.        ,
        1.        ],
       [5.38516481, 4.47213595, 5.38516481, ..., 5.38516481, 5.38516481,
        5.38516481],
       [0.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

array([[1.41421356, 1.41421356, 1.        , ..., 1.41421356, 1.        ,
        1.41421356],
       [5.09901951, 5.09901951, 5.        , ..., 5.09901951, 5.        ,
        5.09901951],
       [0.        , 0.        , 1.        , ..., 0.        , 1.        ,
        0.        ],
       ...,
       [3.16227766, 3.16227766, 2.23606798, ..., 3.16227766, 2.23606798,
        3.16227766],
       [1.        , 1.        , 0.        , ..., 1.        , 0.        ,
        1.        ],
       [0.        , 0.        , 1.        , ..., 0.        , 1.        ,
        0.        ]])

array([[ 3.        ,  3.        ,  3.        ,  3.16227766,  3.16227766,
         3.        ,  3.        ,  3.31662479,  3.60555128,  3.        ,
         3.        ,  3.16227766,  3.        ,  3.        ,  3.        ,
         3.        ,  3.        ,  3.        ,  3.        ,  3.        ,
         3.        ,  3.        ,  3.        ,  3.        ,  3.60555128,
         3.16227766,  3.16227766,  3.        ,  3.        ,  3.        ,
         3.        ,  3.        ,  3.16227766,  3.        ,  3.        ,
         3.        ,  3.        ,  3.        ,  3.        ,  3.        ,
         3.        ,  3.16227766,  3.        ,  3.        ,  3.        ,
         3.16227766,  3.        ,  3.        ,  3.        ,  3.16227766,
         3.        ,  3.        ,  3.        ,  3.        ,  3.16227766,
         3.16227766,  3.        ,  3.        ,  3.16227766,  3.        ,
         3.        ,  3.        ,  3.        ,  3.        ,  3.        ,
         3.        ,  3.16227766,  3.        ,  3. 

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 1.        ,  1.        ,  1.        , ...,  1.        ,
         1.        ,  1.        ],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [11.22497216, 11.22497216, 11.22497216, ..., 11.22497216,
        11.22497216, 11.22497216],
       [ 1.        ,  1.        ,  1.        , ...,  1.        ,
         1.        ,  1.        ]])

array([[ 5.        ,  5.        ,  5.        ,  4.12310563,  5.        ,
         5.        ,  5.        ,  5.        ,  5.        ,  4.47213595,
         4.47213595,  5.        ,  5.        ,  4.47213595,  5.        ,
         5.        ,  5.        ,  5.        ,  5.        ,  4.47213595,
         5.        ,  5.        ,  5.        ,  5.        ,  5.        ,
         5.        ,  5.        ,  5.        ,  5.        ,  5.        ,
         5.        ,  5.        ,  5.        ,  5.        ,  5.        ,
         5.        ,  4.12310563,  5.        ,  5.        ,  4.58257569,
         5.        ,  5.        ,  5.        ,  4.58257569,  5.        ,
         4.12310563,  4.58257569,  4.47213595,  5.        ,  5.        ,
         5.        ,  5.        ,  5.        ,  4.47213595,  5.        ,
         5.        ,  5.        ,  4.12310563,  5.        ,  4.12310563,
         5.        ,  5.        ,  5.        ,  5.        ,  5.        ,
         5.        ,  5.        ,  5.        ,  5. 

array([[0.        , 0.        , 1.        , ..., 0.        , 1.        ,
        1.        ],
       [1.        , 1.        , 1.41421356, ..., 1.        , 1.41421356,
        1.41421356],
       [0.        , 0.        , 1.        , ..., 0.        , 1.        ,
        1.        ],
       ...,
       [4.24264069, 4.24264069, 3.31662479, ..., 4.24264069, 3.31662479,
        3.31662479],
       [0.        , 0.        , 1.        , ..., 0.        , 1.        ,
        1.        ],
       [0.        , 0.        , 1.        , ..., 0.        , 1.        ,
        1.        ]])

array([[4.        , 4.        , 4.12310563, ..., 4.        , 4.12310563,
        4.12310563],
       [2.23606798, 2.23606798, 2.        , ..., 2.23606798, 2.        ,
        2.        ],
       [2.        , 2.        , 2.23606798, ..., 2.        , 2.23606798,
        2.23606798],
       ...,
       [1.41421356, 1.41421356, 1.        , ..., 1.41421356, 1.        ,
        1.        ],
       [0.        , 0.        , 1.        , ..., 0.        , 1.        ,
        1.        ],
       [1.41421356, 1.41421356, 1.        , ..., 1.41421356, 1.        ,
        1.        ]])

array([[ 4.        ,  1.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 4.12310563,  1.41421356,  1.        , ...,  1.        ,
         1.        ,  1.        ],
       [ 4.        ,  1.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [13.41640786, 13.74772708, 14.        , ..., 14.        ,
        14.        , 14.        ],
       [ 9.2736185 ,  9.43398113,  9.69535971, ...,  9.69535971,
         9.69535971,  9.69535971],
       [ 3.        ,  0.        ,  1.        , ...,  1.        ,
         1.        ,  1.        ]])

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [1.73205081, 1.73205081, 1.73205081, ..., 1.73205081, 1.73205081,
        1.73205081],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [2.        , 2.        , 2.        , ..., 2.        , 2.        ,
        2.        ],
       [2.        , 2.        , 2.        , ..., 2.        , 2.        ,
        2.        ]])

array([[ 0.        ,  1.        ,  0.        , ...,  2.        ,
         2.        ,  0.        ],
       [ 1.        ,  1.41421356,  1.        , ...,  2.23606798,
         2.23606798,  1.        ],
       [ 0.        ,  1.        ,  0.        , ...,  2.        ,
         2.        ,  0.        ],
       ...,
       [ 9.48683298,  8.54400375,  9.48683298, ...,  7.61577311,
         7.61577311,  9.48683298],
       [17.02938637, 16.40121947, 17.02938637, ..., 15.8113883 ,
        15.8113883 , 17.02938637],
       [13.74772708, 13.19090596, 13.74772708, ..., 12.68857754,
        12.68857754, 13.74772708]])

array([[1.        , 1.        , 1.        , ..., 1.41421356, 1.        ,
        1.41421356],
       [6.40312424, 6.40312424, 6.40312424, ..., 6.32455532, 6.40312424,
        6.32455532],
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        1.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        1.        ],
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        1.        ],
       [3.        , 3.        , 3.        , ..., 2.        , 3.        ,
        2.        ]])

array([[7.21110255, 7.21110255, 7.21110255, 7.21110255, 7.21110255,
        6.70820393, 7.21110255, 7.21110255, 7.21110255, 7.21110255,
        7.21110255, 7.21110255, 7.21110255, 7.21110255, 6.70820393,
        7.21110255, 7.21110255, 7.21110255, 6.70820393, 7.21110255,
        7.21110255, 7.21110255, 7.21110255, 6.70820393, 7.21110255,
        7.21110255, 7.21110255, 7.21110255, 7.21110255, 7.21110255,
        7.21110255, 6.70820393, 7.21110255, 7.21110255, 7.21110255,
        7.21110255, 7.21110255, 7.21110255, 7.21110255, 6.70820393,
        7.21110255, 6.70820393, 7.21110255, 7.21110255, 7.21110255,
        7.21110255, 7.21110255, 6.70820393, 7.21110255, 6.70820393,
        6.70820393, 7.21110255, 7.21110255, 7.21110255, 7.21110255,
        7.21110255, 7.21110255, 7.21110255],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
   

array([[0.        , 0.        , 0.        , ..., 1.        , 2.        ,
        1.        ],
       [1.41421356, 1.41421356, 1.41421356, ..., 1.        , 1.41421356,
        1.        ],
       [0.        , 0.        , 0.        , ..., 1.        , 2.        ,
        1.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 2.        ,
        1.        ],
       [1.        , 1.        , 1.        , ..., 0.        , 1.        ,
        0.        ],
       [1.        , 1.        , 1.        , ..., 1.41421356, 2.23606798,
        1.41421356]])

array([[1.        , 0.        , 1.        , ..., 1.        , 0.        ,
        2.        ],
       [1.        , 0.        , 1.        , ..., 1.        , 0.        ,
        2.        ],
       [2.        , 3.        , 2.        , ..., 2.        , 3.        ,
        1.        ],
       ...,
       [1.41421356, 2.23606798, 1.41421356, ..., 1.41421356, 2.23606798,
        1.        ],
       [1.        , 0.        , 1.        , ..., 1.        , 0.        ,
        2.        ],
       [3.16227766, 3.31662479, 3.16227766, ..., 3.16227766, 3.31662479,
        3.31662479]])

array([[0.        , 3.        , 0.        , ..., 1.        , 1.        ,
        0.        ],
       [3.        , 0.        , 3.        , ..., 2.        , 2.        ,
        3.        ],
       [2.        , 3.60555128, 2.        , ..., 2.23606798, 2.23606798,
        2.        ],
       ...,
       [1.        , 2.        , 1.        , ..., 0.        , 0.        ,
        1.        ],
       [0.        , 3.        , 0.        , ..., 1.        , 1.        ,
        0.        ],
       [2.        , 1.        , 2.        , ..., 1.        , 1.        ,
        2.        ]])

array([[ 2.23606798,  1.41421356,  1.41421356, ...,  1.41421356,
         1.41421356,  1.41421356],
       [94.43516294, 94.67312185, 94.67312185, ..., 94.50396817,
        94.67312185, 94.67312185],
       [23.43074903, 25.33771892, 25.33771892, ..., 24.04163056,
        25.33771892, 25.33771892],
       ...,
       [ 2.        ,  1.        ,  1.        , ...,  1.        ,
         1.        ,  1.        ],
       [ 5.38516481,  5.09901951,  5.09901951, ...,  5.09901951,
         5.09901951,  5.09901951],
       [ 4.12310563,  7.07106781,  7.07106781, ...,  5.09901951,
         7.07106781,  7.07106781]])

array([[2.23606798, 1.41421356, 2.23606798, ..., 2.23606798, 2.23606798,
        2.23606798],
       [0.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       ...,
       [2.        , 2.        , 2.        , ..., 2.        , 2.        ,
        2.        ],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [2.23606798, 2.23606798, 2.23606798, ..., 2.23606798, 2.23606798,
        2.23606798]])

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [3.74165739, 3.74165739, 3.74165739, ..., 3.74165739, 3.74165739,
        3.74165739],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [2.        , 2.        , 2.        , ..., 2.        , 2.        ,
        2.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

array([[2.23606798, 1.        , 1.41421356, ..., 1.        , 1.        ,
        1.41421356],
       [3.        , 3.        , 2.82842712, ..., 3.        , 3.        ,
        2.82842712],
       [1.        , 1.        , 0.        , ..., 1.        , 1.        ,
        0.        ],
       ...,
       [0.        , 2.        , 1.        , ..., 2.        , 2.        ,
        1.        ],
       [1.        , 1.        , 0.        , ..., 1.        , 1.        ,
        0.        ],
       [2.        , 0.        , 1.        , ..., 0.        , 0.        ,
        1.        ]])

array([[1., 0., 1., ..., 1., 0., 0.],
       [1., 0., 1., ..., 1., 0., 0.],
       [1., 0., 1., ..., 1., 0., 0.],
       ...,
       [1., 2., 1., ..., 1., 2., 2.],
       [1., 0., 1., ..., 1., 0., 0.],
       [1., 0., 1., ..., 1., 0., 0.]])

array([[0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [2.23606798, 2.23606798, 2.23606798, ..., 1.41421356, 2.23606798,
        2.23606798],
       ...,
       [1.41421356, 1.41421356, 1.41421356, ..., 1.        , 1.41421356,
        1.41421356],
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [3.        , 3.        , 3.        , ..., 2.44948974, 3.        ,
        3.        ]])

array([[0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [7.48331477, 7.48331477, 7.48331477, ..., 7.28010989, 7.48331477,
        7.48331477],
       [1.        , 1.        , 1.        , ..., 0.        , 1.        ,
        1.        ],
       ...,
       [1.        , 1.        , 1.        , ..., 1.41421356, 1.        ,
        1.        ],
       [2.        , 2.        , 2.        , ..., 2.23606798, 2.        ,
        2.        ],
       [2.23606798, 2.23606798, 2.23606798, ..., 1.41421356, 2.23606798,
        2.23606798]])

array([[ 1.        ,  1.        ,  1.        , ...,  1.        ,
         1.41421356,  1.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       [11.78982612, 11.78982612, 11.78982612, ..., 11.78982612,
        10.86278049, 11.78982612],
       ...,
       [ 1.        ,  1.        ,  1.        , ...,  1.        ,
         1.41421356,  1.        ],
       [ 1.41421356,  1.41421356,  1.41421356, ...,  1.41421356,
         1.        ,  1.41421356],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         1.        ,  0.        ]])

array([[2.        , 2.        , 2.23606798, ..., 2.        , 2.23606798,
        2.        ],
       [0.        , 0.        , 1.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.        , 1.        ,
        0.        ],
       ...,
       [1.        , 1.        , 1.41421356, ..., 1.        , 1.41421356,
        1.        ],
       [0.        , 0.        , 1.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.        , 1.        ,
        0.        ]])

array([[1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [5.09901951, 5.09901951, 5.09901951, ..., 5.09901951, 5.09901951,
        5.09901951],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [3.31662479, 3.31662479, 3.31662479, ..., 3.31662479, 3.31662479,
        3.31662479]])

array([[1.41421356, 1.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       [1.41421356, 1.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       [1.73205081, 1.41421356, 1.41421356, ..., 1.        , 1.        ,
        1.        ],
       ...,
       [1.        , 0.        , 0.        , ..., 1.        , 1.        ,
        1.        ],
       [1.73205081, 1.41421356, 1.41421356, ..., 1.        , 1.        ,
        1.        ],
       [1.73205081, 1.41421356, 1.41421356, ..., 1.        , 1.        ,
        1.        ]])

array([[ 3.        ,  4.12310563,  3.        , ...,  3.        ,
         3.16227766,  3.16227766],
       [10.        ,  9.16515139, 10.        , ..., 10.        ,
        10.04987562, 10.04987562],
       [13.60147051, 11.87434209, 13.60147051, ..., 13.60147051,
        14.07124728, 13.19090596],
       ...,
       [ 1.        ,  3.60555128,  1.        , ...,  1.        ,
         0.        ,  2.        ],
       [ 1.        ,  3.60555128,  1.        , ...,  1.        ,
         0.        ,  2.        ],
       [ 0.        ,  2.82842712,  0.        , ...,  0.        ,
         1.        ,  1.        ]])

array([[0.        , 0.        , 1.        , ..., 1.        , 3.31662479,
        1.        ],
       [0.        , 0.        , 1.        , ..., 1.        , 3.31662479,
        1.        ],
       [0.        , 0.        , 1.        , ..., 1.        , 3.31662479,
        1.        ],
       ...,
       [2.44948974, 2.44948974, 2.23606798, ..., 2.23606798, 3.60555128,
        2.23606798],
       [3.60555128, 3.60555128, 3.16227766, ..., 3.16227766, 4.47213595,
        3.16227766],
       [2.23606798, 2.23606798, 1.41421356, ..., 1.41421356, 3.46410162,
        1.41421356]])

array([[7.28010989, 7.28010989, 6.40312424, ..., 7.28010989, 6.78232998,
        7.28010989],
       [2.82842712, 2.82842712, 2.        , ..., 2.82842712, 2.23606798,
        2.82842712],
       [8.06225775, 8.06225775, 7.        , ..., 8.06225775, 7.48331477,
        8.06225775],
       ...,
       [1.        , 1.        , 1.        , ..., 1.        , 0.        ,
        1.        ],
       [2.44948974, 2.44948974, 1.41421356, ..., 2.44948974, 1.73205081,
        2.44948974],
       [1.        , 1.        , 2.23606798, ..., 1.        , 1.41421356,
        1.        ]])

array([[6.08276253, 6.08276253, 6.08276253, ..., 5.19615242, 6.08276253,
        5.09901951],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        0.        ],
       [7.07106781, 7.07106781, 7.07106781, ..., 6.164414  , 7.07106781,
        6.70820393],
       ...,
       [0.        , 0.        , 0.        , ..., 1.41421356, 0.        ,
        1.        ],
       [1.        , 1.        , 1.        , ..., 1.73205081, 1.        ,
        1.41421356],
       [0.        , 0.        , 0.        , ..., 1.41421356, 0.        ,
        1.        ]])

array([[ 1.        ,  1.        ,  1.41421356, ...,  1.        ,
         1.        ,  2.44948974],
       [ 1.        ,  1.        ,  0.        , ...,  1.        ,
         1.        ,  1.41421356],
       [10.39230485, 10.39230485,  9.8488578 , ..., 10.39230485,
        10.39230485,  8.77496439],
       ...,
       [ 0.        ,  0.        ,  1.        , ...,  0.        ,
         0.        ,  2.23606798],
       [ 1.        ,  1.        ,  0.        , ...,  1.        ,
         1.        ,  1.41421356],
       [ 0.        ,  0.        ,  1.        , ...,  0.        ,
         0.        ,  2.23606798]])

array([[1.41421356, 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [0.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

array([[4.        , 4.        , 4.12310563, ..., 4.        , 4.12310563,
        4.        ],
       [0.        , 0.        , 1.        , ..., 0.        , 1.        ,
        0.        ],
       [1.        , 1.        , 1.41421356, ..., 1.        , 1.41421356,
        1.        ],
       ...,
       [0.        , 0.        , 1.        , ..., 0.        , 1.        ,
        0.        ],
       [1.        , 1.        , 1.41421356, ..., 1.        , 1.41421356,
        1.        ],
       [2.        , 2.        , 2.23606798, ..., 2.        , 2.23606798,
        2.        ]])

array([[1.73205081, 0.        , 0.        , ..., 2.        , 0.        ,
        1.        ],
       [1.73205081, 0.        , 0.        , ..., 2.        , 0.        ,
        1.        ],
       [4.12310563, 5.09901951, 5.09901951, ..., 3.16227766, 5.09901951,
        4.12310563],
       ...,
       [2.        , 1.        , 1.        , ..., 2.23606798, 1.        ,
        1.41421356],
       [1.73205081, 0.        , 0.        , ..., 2.        , 0.        ,
        1.        ],
       [1.41421356, 1.        , 1.        , ..., 1.        , 1.        ,
        0.        ]])

array([[2.        , 2.23606798, 0.        , ..., 0.        , 1.        ,
        0.        ],
       [1.41421356, 1.        , 3.16227766, ..., 3.16227766, 2.23606798,
        3.16227766],
       [2.        , 2.23606798, 0.        , ..., 0.        , 1.        ,
        0.        ],
       ...,
       [1.73205081, 1.41421356, 1.73205081, ..., 1.73205081, 1.41421356,
        1.73205081],
       [1.        , 0.        , 2.23606798, ..., 2.23606798, 1.41421356,
        2.23606798],
       [2.        , 2.23606798, 0.        , ..., 0.        , 1.        ,
        0.        ]])

array([[ 5.09901951,  3.74165739,  5.09901951, ...,  4.35889894,
         5.09901951,  5.09901951],
       [ 2.23606798,  2.23606798,  2.23606798, ...,  1.41421356,
         2.23606798,  2.23606798],
       [ 6.40312424,  4.58257569,  6.40312424, ...,  5.47722558,
         6.40312424,  6.40312424],
       ...,
       [41.73727351, 41.68932717, 41.73727351, ..., 41.07310556,
        41.73727351, 41.73727351],
       [ 0.        ,  2.        ,  0.        , ...,  1.73205081,
         0.        ,  0.        ],
       [ 3.16227766,  1.41421356,  3.16227766, ...,  2.23606798,
         3.16227766,  3.16227766]])

array([[0.        , 3.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 3.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [1.        , 3.16227766, 1.        , ..., 1.41421356, 1.        ,
        1.        ],
       ...,
       [2.23606798, 1.41421356, 2.23606798, ..., 1.41421356, 2.23606798,
        2.23606798],
       [0.        , 3.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 3.        , 0.        , ..., 1.        , 0.        ,
        0.        ]])

array([[1.        , 1.        , 1.        , ..., 1.        , 0.        ,
        1.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [1.        , 1.        , 1.        , ..., 1.        , 1.41421356,
        1.        ],
       ...,
       [3.60555128, 3.60555128, 3.60555128, ..., 3.60555128, 2.82842712,
        3.60555128],
       [2.        , 2.        , 2.        , ..., 2.        , 2.23606798,
        2.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ]])

array([[0.        , 1.        , 1.        , ..., 0.        , 1.        ,
        0.        ],
       [3.16227766, 3.        , 3.        , ..., 3.16227766, 3.        ,
        3.16227766],
       [1.        , 0.        , 0.        , ..., 1.        , 0.        ,
        1.        ],
       ...,
       [0.        , 1.        , 1.        , ..., 0.        , 1.        ,
        0.        ],
       [1.        , 0.        , 0.        , ..., 1.        , 0.        ,
        1.        ],
       [0.        , 1.        , 1.        , ..., 0.        , 1.        ,
        0.        ]])

array([[2.        , 2.        , 4.24264069, 2.        , 2.23606798,
        2.23606798, 2.        , 2.        , 2.23606798, 2.23606798,
        2.23606798, 2.        , 2.        , 2.23606798, 2.        ,
        2.23606798, 2.        , 2.        , 2.23606798, 2.23606798,
        2.23606798, 2.23606798, 2.        , 2.23606798, 2.82842712,
        2.23606798, 2.44948974, 2.23606798, 2.        , 2.23606798,
        3.        , 2.        , 2.23606798, 2.        , 2.23606798,
        2.23606798, 2.23606798, 3.60555128, 2.23606798, 2.23606798,
        2.23606798, 2.64575131, 2.44948974, 2.        , 2.23606798,
        2.23606798, 2.23606798, 2.        , 2.23606798, 2.        ,
        2.23606798, 2.        , 2.23606798, 2.        , 2.82842712,
        2.23606798, 2.23606798, 2.23606798, 2.23606798, 2.23606798,
        2.23606798, 2.64575131, 2.23606798, 2.        , 2.23606798,
        2.23606798, 2.23606798, 2.23606798, 2.23606798, 2.23606798,
        2.23606798, 2.23606798, 2.        , 2.23

array([[ 3.16227766,  3.16227766,  3.16227766, ...,  3.16227766,
         3.16227766,  3.16227766],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 1.        ,  1.        ,  1.        , ...,  1.        ,
         1.        ,  1.        ],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [43.23193264, 43.23193264, 43.23193264, ..., 43.23193264,
        43.23193264, 43.23193264]])

array([[1.        , 1.        , 1.        , ..., 0.        , 1.        ,
        1.        ],
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [5.09901951, 5.09901951, 5.09901951, ..., 5.        , 5.09901951,
        5.09901951],
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ]])

array([[3.60555128, 3.60555128, 3.60555128, 3.60555128, 3.60555128,
        3.60555128, 3.60555128, 3.60555128, 3.60555128, 3.60555128,
        3.60555128, 3.60555128, 3.60555128, 3.60555128, 3.60555128,
        3.60555128, 3.60555128, 3.60555128, 3.60555128, 3.60555128,
        3.60555128, 2.82842712, 3.60555128, 3.60555128, 3.60555128,
        3.60555128, 3.60555128, 3.60555128, 2.23606798, 3.60555128,
        3.60555128, 3.60555128, 3.60555128, 3.60555128, 3.60555128,
        3.60555128, 3.60555128, 3.60555128, 3.60555128, 3.60555128,
        3.60555128, 3.60555128, 3.60555128, 2.82842712, 3.60555128,
        3.60555128, 3.60555128, 2.82842712, 3.60555128, 3.60555128,
        3.60555128, 2.23606798, 3.60555128, 3.60555128, 3.60555128,
        3.60555128]])

array([[1.41421356, 1.41421356, 2.23606798, ..., 1.41421356, 1.        ,
        1.41421356],
       [1.        , 1.        , 2.        , ..., 1.        , 0.        ,
        1.        ],
       [6.4807407 , 6.4807407 , 6.40312424, ..., 6.4807407 , 6.70820393,
        6.4807407 ],
       ...,
       [1.        , 1.        , 2.        , ..., 1.        , 0.        ,
        1.        ],
       [1.41421356, 1.41421356, 2.23606798, ..., 1.41421356, 1.        ,
        1.41421356],
       [0.        , 0.        , 1.        , ..., 0.        , 1.        ,
        0.        ]])

array([[0.        , 1.        , 1.        , 0.        , 3.        ,
        0.        , 2.        , 1.        , 0.        , 0.        ,
        0.        , 0.        , 1.        , 0.        , 1.        ,
        0.        , 1.        , 0.        , 1.        , 0.        ,
        1.41421356, 0.        , 0.        , 1.        , 2.23606798,
        0.        , 0.        , 4.        , 4.24264069, 1.        ,
        2.        , 1.41421356, 1.        , 1.        , 0.        ,
        0.        , 1.        , 1.        , 2.        , 0.        ,
        1.        , 1.        , 0.        , 0.        , 1.        ,
        3.16227766, 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 0.        , 2.23606798,
        1.        , 0.        ],
       [1.        , 0.        , 0.        , 1.        , 2.        ,
        1.        , 1.        , 0.        , 1.        , 1.        ,
        1.     

array([[ 1.41421356,  1.        ,  1.        , ...,  1.        ,
         1.        ,  2.23606798],
       [37.22902094, 37.32291521, 37.32291521, ..., 37.32291521,
        37.32291521, 37.16180835],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  2.        ],
       ...,
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  2.        ],
       [ 0.        ,  1.        ,  1.        , ...,  1.        ,
         1.        ,  1.        ],
       [ 4.47213595,  5.        ,  5.        , ...,  5.        ,
         5.        ,  4.12310563]])

array([[0.        , 1.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        1.        , 0.        , 1.        , 0.        , 1.        ,
        1.        , 0.        , 1.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.        , 0.        ,
        1.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 1.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.        , 0.        , 1.        , 1.        ,
        0.        , 1.        , 1.        , 0.        , 0.        ,
        1.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.  

array([[ 3.16227766,  1.        ,  1.        ,  1.        ,  1.41421356,
         1.41421356,  1.        ,  2.23606798,  1.41421356,  1.        ,
         1.        ,  1.41421356,  1.41421356,  1.        ,  1.        ,
         3.16227766,  1.41421356,  3.16227766,  1.41421356,  1.41421356,
         3.16227766,  1.        ,  2.23606798,  6.08276253,  1.41421356,
         1.        ,  1.        ,  1.41421356,  1.41421356,  1.41421356,
         1.41421356,  1.41421356,  1.41421356,  2.44948974,  3.16227766,
         2.23606798,  2.23606798,  1.        ,  2.23606798,  2.44948974,
         3.31662479,  1.        ,  1.41421356,  1.        ,  1.41421356,
         4.12310563,  4.12310563,  1.        ,  1.41421356,  1.        ,
         1.        ,  2.23606798,  1.41421356,  1.        ,  1.41421356,
         2.23606798,  2.44948974,  1.41421356,  1.41421356,  1.41421356,
         3.87298335,  1.41421356,  1.        ,  1.        ,  2.23606798,
         1.41421356,  3.74165739,  9.32737905,  1.7

array([[ 1.        ,  8.66025404,  5.        , ...,  2.        ,
         0.        ,  2.        ],
       [ 3.        ,  9.11043358,  5.        , ...,  3.16227766,
         3.16227766,  3.16227766],
       [ 1.41421356,  8.71779789,  5.09901951, ...,  2.23606798,
         1.        ,  2.23606798],
       ...,
       [74.75961477, 73.74957627, 74.43789358, ..., 74.65922582,
        74.87322619, 74.65922582],
       [ 1.41421356,  8.71779789,  3.16227766, ...,  1.        ,
         2.23606798,  1.        ],
       [19.02629759, 17.54992877, 18.81488772, ..., 18.89444363,
        19.20937271, 18.89444363]])

array([[16.18641406, 15.29705854, 16.18641406, 15.55634919, 16.18641406,
        15.68438714, 15.84297952, 16.18641406, 16.18641406, 16.18641406,
        15.84297952, 15.84297952, 15.16575089, 15.84297952, 16.58312395,
        15.55634919, 15.55634919, 15.16575089, 15.55634919, 16.18641406,
        15.16575089, 15.55634919, 15.84297952, 15.84297952, 15.32970972,
        16.58312395, 15.55634919, 15.55634919, 15.55634919, 15.42724862,
        15.84297952, 15.55634919, 16.58312395, 15.84297952, 15.55634919,
        16.58312395, 15.16575089, 15.55634919, 15.16575089, 15.84297952,
        15.13274595, 15.55634919, 15.55634919, 16.58312395, 15.06651917,
        15.8113883 , 16.18641406, 21.42428529, 16.18641406, 16.58312395,
        15.55634919, 15.84297952, 15.32970972, 16.58312395, 15.06651917,
        15.55634919, 16.58312395, 15.32970972, 15.55634919, 15.55634919,
        16.58312395],
       [ 3.60555128,  4.35889894,  3.60555128,  4.12310563,  3.60555128,
         5.19615242,  3.74165

array([[ 2.82842712,  2.82842712,  2.23606798,  2.23606798,  2.        ,
         2.23606798,  2.23606798,  2.        ,  2.82842712,  2.23606798,
         6.164414  ,  2.        ,  2.23606798,  2.82842712,  2.23606798,
         2.23606798,  2.23606798,  2.23606798,  2.82842712,  4.58257569,
         3.60555128,  2.23606798,  2.        ,  4.24264069,  4.58257569,
         2.23606798,  4.47213595,  2.23606798,  3.60555128,  2.23606798,
         2.82842712,  2.        ,  2.        ,  2.82842712,  3.        ,
         9.59166305,  2.82842712,  2.23606798,  2.82842712,  3.60555128,
         2.82842712,  2.82842712,  2.        ,  2.23606798,  2.        ,
         2.23606798,  2.23606798,  3.60555128,  2.82842712,  2.        ,
         2.23606798,  2.23606798,  2.23606798,  2.23606798,  2.        ,
         2.23606798,  2.23606798,  2.23606798,  2.        ,  7.54983444,
         2.23606798,  2.        ,  6.32455532,  2.23606798,  2.82842712],
       [ 1.41421356,  3.16227766,  1.        ,  2.

array([[ 3.16227766,  1.41421356,  4.12310563, ...,  1.41421356,
         1.        ,  2.23606798],
       [22.93468988, 23.53720459, 22.69361144, ..., 23.53720459,
        23.89560629, 23.21637353],
       [ 8.06225775,  7.81024968,  8.36660027, ...,  7.81024968,
         7.87400787,  7.87400787],
       ...,
       [ 3.        ,  2.23606798,  3.74165739, ...,  2.23606798,
         2.44948974,  2.44948974],
       [ 3.74165739,  3.16227766,  4.35889894, ...,  3.16227766,
         3.31662479,  3.31662479],
       [ 3.        ,  1.        ,  4.        , ...,  1.        ,
         0.        ,  2.        ]])

array([[35.86084215, 35.73513677, 35.86084215, ..., 36.19392214,
        35.7211422 , 36.01388621],
       [ 5.91607978,  6.164414  ,  5.91607978, ...,  5.91607978,
         6.55743852,  5.83095189],
       [ 3.60555128,  3.16227766,  3.60555128, ...,  5.        ,
         6.70820393,  4.24264069],
       ...,
       [ 8.60232527,  8.30662386,  8.60232527, ...,  9.48683298,
         8.94427191,  9.        ],
       [ 1.        ,  2.        ,  1.        , ...,  1.        ,
         6.244998  ,  0.        ],
       [ 3.16227766,  3.60555128,  3.16227766, ...,  3.16227766,
         6.92820323,  3.        ]])

array([[37.97367509, 38.15756806, 38.27531842, ..., 37.57658846,
        37.69615365, 38.60051813],
       [ 3.16227766,  2.44948974,  2.23606798, ...,  4.24264069,
         4.12310563,  1.41421356],
       [38.58756276, 38.48376281, 38.78143886, ..., 38.11823711,
        38.41874542, 39.        ],
       ...,
       [ 2.23606798,  1.73205081,  1.41421356, ...,  3.31662479,
         3.16227766,  1.        ],
       [ 1.41421356,  1.41421356,  1.        , ...,  2.44948974,
         2.23606798,  1.41421356],
       [ 3.        ,  2.23606798,  2.        , ...,  4.12310563,
         4.        ,  1.        ]])

array([[2.82842712, 3.        , 2.82842712, ..., 2.82842712, 2.82842712,
        3.        ],
       [1.        , 2.        , 1.        , ..., 1.        , 1.        ,
        2.        ],
       [3.16227766, 3.31662479, 3.16227766, ..., 3.16227766, 3.16227766,
        3.31662479],
       ...,
       [7.68114575, 7.61577311, 7.68114575, ..., 7.68114575, 7.68114575,
        7.61577311],
       [4.12310563, 4.        , 4.12310563, ..., 4.12310563, 4.12310563,
        4.        ],
       [1.        , 2.        , 1.        , ..., 1.        , 1.        ,
        2.        ]])

array([[ 9.2736185 ,  8.60232527,  9.69535971, ...,  9.94987437,
         8.1240384 ,  7.68114575],
       [ 7.61577311,  7.34846923,  9.05538514, ...,  8.06225775,
         7.07106781,  7.        ],
       [39.92492956, 39.67366885, 39.2173431 , ..., 40.01249805,
        39.8246155 , 39.81205847],
       ...,
       [ 3.        ,  4.12310563,  6.70820393, ...,  2.        ,
         5.        ,  6.        ],
       [11.        , 10.72380529,  9.74679434, ..., 10.86278049,
        11.53256259, 11.91637529],
       [ 3.74165739,  3.46410162,  4.        , ...,  3.60555128,
         4.69041576,  5.38516481]])

array([[ 2.23606798,  3.60555128,  2.23606798, ...,  2.        ,
         2.23606798,  2.44948974],
       [ 1.        ,  3.        ,  1.        , ...,  0.        ,
         1.        ,  1.41421356],
       [23.28089345, 23.4520788 , 23.28089345, ..., 23.2594067 ,
        23.28089345, 22.86919325],
       ...,
       [ 3.16227766,  4.24264069,  3.16227766, ...,  3.        ,
         3.16227766,  3.31662479],
       [ 0.        ,  4.        ,  0.        , ...,  1.        ,
         2.        ,  2.23606798],
       [ 0.        ,  4.        ,  0.        , ...,  1.        ,
         2.        ,  2.23606798]])

array([[ 2.23606798,  2.82842712,  2.23606798, ...,  2.23606798,
         2.23606798,  2.        ],
       [19.87460691, 19.6468827 , 19.87460691, ..., 19.87460691,
        19.87460691, 20.14944168],
       [ 1.41421356,  2.23606798,  1.41421356, ...,  1.41421356,
         1.41421356,  1.        ],
       ...,
       [ 2.82842712,  2.23606798,  2.82842712, ...,  2.82842712,
         2.82842712,  3.60555128],
       [ 1.        ,  1.41421356,  1.        , ...,  1.        ,
         1.        ,  1.41421356],
       [ 3.        ,  3.16227766,  3.        , ...,  3.        ,
         3.        ,  3.16227766]])

array([[ 3.16227766,  3.16227766,  3.16227766,  3.        ,  3.31662479,
         3.16227766,  5.83095189,  3.        , 13.07669683,  3.16227766,
         5.83095189,  3.16227766,  4.24264069,  3.16227766,  4.24264069,
         3.        ,  3.16227766,  3.        ,  3.60555128,  3.16227766,
         8.24621125,  3.        ,  4.24264069,  3.60555128,  3.16227766,
         3.60555128,  3.16227766,  3.16227766,  3.16227766,  3.60555128,
         6.        ,  3.60555128,  3.16227766,  4.24264069,  3.31662479,
         3.        ,  3.60555128,  3.60555128,  3.        ,  4.24264069,
         5.38516481,  6.244998  ,  3.60555128,  3.60555128,  3.16227766,
         3.        ,  4.69041576,  5.83095189,  6.40312424,  3.60555128,
         3.16227766,  3.60555128,  6.55743852,  7.21110255,  3.        ,
         4.24264069,  3.60555128,  3.60555128,  3.16227766],
       [ 1.        ,  1.        ,  1.        ,  0.        ,  1.41421356,
         1.        ,  5.        ,  0.        , 12.72792206,  1.

array([[ 2.        ,  2.        ,  2.23606798, ...,  2.        ,
         2.        ,  2.23606798],
       [17.54992877, 17.54992877, 17.23368794, ..., 17.54992877,
        17.54992877, 17.91647287],
       [ 8.54400375,  8.54400375,  8.60232527, ...,  8.54400375,
         8.54400375,  8.60232527],
       ...,
       [26.01922366, 26.01922366, 25.8069758 , ..., 26.01922366,
        26.01922366, 26.26785107],
       [ 2.23606798,  2.23606798,  2.        , ...,  2.23606798,
         2.23606798,  2.82842712],
       [41.19465985, 41.19465985, 41.20679556, ..., 41.19465985,
        41.19465985, 41.20679556]])

array([[ 1.        ,  2.23606798,  1.41421356, ...,  1.41421356,
         1.        ,  2.23606798],
       [ 1.        ,  1.        ,  0.        , ...,  0.        ,
         1.        ,  1.        ],
       [ 6.40312424,  6.08276253,  6.164414  , ...,  6.164414  ,
         6.40312424,  6.08276253],
       ...,
       [ 3.        ,  3.        ,  2.82842712, ...,  2.82842712,
         3.        ,  3.        ],
       [10.86278049, 10.86278049, 10.81665383, ..., 10.81665383,
        10.86278049, 10.86278049],
       [ 3.60555128,  3.        ,  3.16227766, ...,  3.16227766,
         3.60555128,  3.        ]])

array([[ 17.29161647,   7.61577311,  12.36931688,   7.61577311,
          6.70820393,   7.61577311,  12.36931688,  13.34166406,
         11.40175425,   8.54400375,   9.48683298, 158.1107207 ,
          5.83095189,   6.70820393,   9.48683298,   9.48683298,
          5.83095189,   9.48683298,   9.48683298,  11.40175425,
          8.54400375,   9.48683298,   9.48683298, 121.17755568,
          9.48683298, 155.41878908,   6.70820393,   5.83095189,
          7.61577311,   9.48683298,   6.70820393,  11.40175425,
          5.        , 124.99599994,   6.70820393,   4.24264069,
          6.70820393, 103.95672176,  15.06651917,  10.44030651,
          6.70820393,   6.70820393, 115.01738999,   7.61577311,
          9.48683298,  10.44030651,   5.83095189,   9.48683298,
         13.07669683,   5.        ,  11.5758369 ,  13.34166406,
         95.34149149,   8.54400375, 139.88209321,   8.54400375,
          8.54400375,  12.36931688,   3.60555128,   5.        ,
        107.97221865,   8.54400375,   8.

array([[ 0.        ,  0.        ,  1.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  1.        ,
         1.        ,  0.        ,  1.        ,  1.        ,  0.        ,
         1.        ,  2.        ,  1.        ,  1.        ,  1.        ,
         2.        ,  0.        ,  0.        ,  1.        ,  1.        ,
         1.73205081,  0.        ,  1.        ,  1.        ,  2.        ,
         1.        ,  3.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         2.        ,  3.        ,  2.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  2.        ,  3.        ,
         2.        ,  0.        ,  0.        ,  1.        ,  3.        ,
         0.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  2.        ,  1.        ,  1.        ,
         0.        ,  1.        ,  2.        ,  1. 

array([[24.2899156 , 24.35159132, 24.45403852, 24.45403852, 24.2899156 ,
        24.35159132, 24.2693222 , 24.2899156 , 24.45403852, 24.2899156 ,
        24.45403852, 24.2693222 , 24.2899156 , 24.2693222 , 24.2899156 ,
        24.2693222 , 24.2899156 , 24.35159132, 24.59674775, 24.35159132,
        24.2693222 , 24.2899156 , 24.2899156 , 24.45403852, 24.35159132,
        24.35159132, 24.2899156 , 24.2899156 , 24.2899156 , 24.2693222 ,
        24.35159132, 24.2693222 , 24.2693222 , 24.2693222 , 24.2693222 ,
        24.2899156 , 25.        , 24.2899156 , 24.35159132, 24.2693222 ,
        24.2899156 , 25.        , 24.2693222 , 24.2693222 , 24.2693222 ,
        24.2693222 , 24.35159132, 24.45403852, 24.35159132, 24.2899156 ,
        24.35159132, 23.4520788 , 24.2899156 ],
       [ 0.        ,  3.        ,  4.        ,  4.        ,  2.        ,
         3.        ,  1.        ,  2.        ,  4.        ,  0.        ,
         4.        ,  1.        ,  2.        ,  1.        ,  0.        ,
   

array([[ 0.        ,  1.        ,  0.        , ...,  1.        ,
         1.        ,  1.        ],
       [13.92838828, 13.74772708, 13.92838828, ..., 13.74772708,
        13.74772708, 13.74772708],
       [ 0.        ,  1.        ,  0.        , ...,  1.        ,
         1.        ,  1.        ],
       ...,
       [ 2.44948974,  2.23606798,  2.44948974, ...,  2.23606798,
         2.23606798,  2.23606798],
       [ 2.23606798,  2.        ,  2.23606798, ...,  2.        ,
         2.        ,  2.        ],
       [ 2.        ,  1.        ,  2.        , ...,  1.        ,
         1.        ,  1.        ]])

array([[0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        2.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        2.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        2.        ],
       ...,
       [1.        , 1.        , 1.        , ..., 1.        , 1.41421356,
        2.23606798],
       [1.        , 1.        , 1.        , ..., 1.        , 1.41421356,
        2.23606798],
       [1.        , 1.        , 1.        , ..., 1.        , 1.41421356,
        2.23606798]])

array([[ 3.16227766,  1.        ,  3.16227766, ...,  2.23606798,
         1.41421356,  1.41421356],
       [ 0.        ,  3.        ,  0.        , ...,  5.        ,
         2.        ,  2.        ],
       [16.43167673, 14.17744688, 16.43167673, ..., 12.84523258,
        14.89966443, 14.89966443],
       ...,
       [ 0.        ,  3.        ,  0.        , ...,  5.        ,
         2.        ,  2.        ],
       [ 2.        ,  3.60555128,  2.        , ...,  5.38516481,
         2.82842712,  2.82842712],
       [ 1.        ,  3.16227766,  1.        , ...,  5.09901951,
         2.23606798,  2.23606798]])

array([[0.        , 0.        , 0.        , ..., 1.        , 4.        ,
        1.        ],
       [3.16227766, 3.16227766, 3.16227766, ..., 3.31662479, 5.09901951,
        3.31662479],
       [5.        , 5.        , 5.        , ..., 5.09901951, 6.40312424,
        5.09901951],
       ...,
       [3.60555128, 3.60555128, 3.60555128, ..., 3.16227766, 3.60555128,
        4.24264069],
       [3.16227766, 3.16227766, 3.16227766, ..., 3.60555128, 5.83095189,
        3.        ],
       [4.        , 4.        , 4.        , ..., 4.12310563, 5.65685425,
        4.12310563]])

array([[ 3.        ,  3.60555128,  4.24264069,  3.        ,  3.60555128,
         3.60555128,  3.60555128,  3.        ,  3.16227766,  5.        ,
         3.60555128,  3.16227766,  3.16227766,  3.16227766,  3.16227766,
         3.16227766,  3.16227766,  3.        ,  3.16227766,  3.        ,
         3.16227766,  5.        ,  3.        ,  3.74165739,  3.16227766,
         3.        ,  3.        ,  3.16227766,  3.        ,  3.60555128,
         4.89897949,  3.        ,  3.16227766,  3.        ,  3.60555128,
         4.35889894,  3.60555128,  3.        ,  3.60555128,  3.        ,
         3.16227766,  3.16227766,  3.        ,  3.        ,  3.16227766,
         3.        ,  3.60555128,  3.60555128,  3.60555128,  3.60555128,
         3.16227766,  3.60555128,  3.16227766,  3.60555128,  3.16227766,
         4.24264069,  3.        ,  3.60555128,  3.        ,  3.16227766],
       [ 1.        ,  2.23606798,  3.16227766,  1.        ,  2.23606798,
         2.23606798,  2.23606798,  1.        ,  1.

array([[1.        , 0.        , 1.        , ..., 0.        , 0.        ,
        3.        ],
       [0.        , 1.        , 0.        , ..., 1.        , 1.        ,
        4.        ],
       [1.73205081, 1.41421356, 1.73205081, ..., 1.41421356, 1.41421356,
        3.31662479],
       ...,
       [9.43398113, 9.2736185 , 9.43398113, ..., 9.2736185 , 9.2736185 ,
        9.43398113],
       [1.        , 0.        , 1.        , ..., 0.        , 0.        ,
        3.        ],
       [0.        , 1.        , 0.        , ..., 1.        , 1.        ,
        4.        ]])

array([[1.        , 1.41421356, 1.        , ..., 1.        , 1.41421356,
        1.        ],
       [0.        , 1.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       ...,
       [4.47213595, 4.12310563, 4.47213595, ..., 4.47213595, 4.12310563,
        4.47213595],
       [1.        , 1.41421356, 1.        , ..., 1.        , 1.41421356,
        1.        ],
       [1.41421356, 1.        , 1.41421356, ..., 1.41421356, 1.        ,
        1.41421356]])

array([[2.82842712, 2.        , 2.        , ..., 2.        , 2.23606798,
        2.        ],
       [0.        , 2.        , 2.        , ..., 2.        , 1.        ,
        2.        ],
       [9.64365076, 8.06225775, 8.06225775, ..., 8.06225775, 8.83176087,
        8.06225775],
       ...,
       [3.60555128, 3.        , 3.        , ..., 3.        , 3.16227766,
        3.        ],
       [1.        , 2.23606798, 2.23606798, ..., 2.23606798, 1.41421356,
        2.23606798],
       [5.38516481, 5.        , 5.        , ..., 5.        , 5.09901951,
        5.        ]])

author_feature  tweet_feature
0000            0000             391.523081
                0001              48.106746
                0010             138.775467
                0011              90.748523
                0100             186.782432
                                    ...    
1101            1000             308.377773
                1001              35.087863
                1010              48.775291
                1100             174.444979
                1110              21.164414
Length: 131, dtype: float64

In [244]:
mine.loc[('0000','0010')]/orig.loc[('0000','0010')]


90.46178343949046

In [240]:
len(fpoe_g.loc[('0000','0000')]['list'][0])

1796

In [245]:
orig

author_feature  tweet_feature
0000            0000             0.290439
                0001             0.453620
                0010             0.431121
                0011             0.203445
                0100             0.498565
                                   ...   
1101            1000             0.758389
                1001             0.318748
                1010             0.369030
                1100             0.303179
                1110             0.273639
Length: 131, dtype: float64

In [246]:
mine

author_feature  tweet_feature
0000            0000             86.0
                0001             25.0
                0010             39.0
                0011             15.0
                0100             57.0
                                 ... 
1101            1000             93.0
                1001             14.0
                1010              0.0
                1100             24.0
                1110              5.0
Length: 131, dtype: float64

In [269]:
from scipy.stats import wasserstein_distance

# np.random.seed(0)
n = 100

Y1 = np.random.randn(n)
Y2 = np.random.randn(n-10) - 2
d =  np.abs(Y1 - Y2.reshape((n-10, 1)))

assignment = linear_sum_assignment(d)
print(d[assignment].sum()/90)       # 1.9777950447866477
print(wasserstein_distance(Y1, Y2))  #
#np.abs(Y1 - Y2.reshape((n, 1)))

1.7175756547887042
1.888756845699202


In [5]:
s=ast.literal_eval(open('hawk-out/neos/solutions-neos-1338421.hawk-pbs5.pyon').read())

In [10]:
f0=pd.DataFrame([{**d, 'val':v} for v,d in s[('0000','0000')]])

In [16]:
f0.sort_values('discount_factor')

discount_factor      corr       val
69         0.900000  0.004300  1.406988
66         0.900000  0.004500  1.880012
71         0.910000  0.004200  3.227481
67         0.910000  0.004300  1.148491
31         0.910000  0.004500  1.077906
..              ...       ...       ...
57         0.996094  0.004300  1.138493
42         0.996094  0.003700  1.384988
11         1.000000  0.004648  0.478144
62         1.000000  0.004700  2.301293
50         1.000000  0.004500  1.472887

[72 rows x 3 columns]

In [3]:
g=sp.sparse.load_npz('../kpm/pokec_full.npz')

In [9]:
g[0:990908//2, 0:990908//2]

<495454x495454 sparse matrix of type '<class 'numpy.float64'>'
	with 20002868 stored elements in Compressed Sparse Row format>